export interface Module {
  id: string;
  name: string;
  shortName: string;
  description: string;
  icon: string;
  category: "comun" | "administrativo" | "auxiliar" | "tec-especifico" | "tec-comun" | "virtual";
  color: string;
  bgColor: string;
  borderColor: string;
  questionFile: string;
}

export const MODULES: Module[] = [

  // ── COMÚN C2 (AUX + ADMIN) ───────────────────────────────────────────────
  { id: "comun-t01", name: "C2 T01: Profesiones Sanitarias", shortName: "T01 Profesiones Sanitarias", description: "Ley 44/2003 de Ordenación de Profesiones Sanitarias", icon: "🏥", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t01" },
  { id: "comun-t02", name: "C2 T02: Cohesión del SNS", shortName: "T02 Cohesión SNS", description: "Ley 16/2003 de Cohesión y Calidad del SNS", icon: "🏥", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t02" },
  { id: "comun-t03", name: "C2 T03: Estatuto Marco", shortName: "T03 Estatuto Marco", description: "Estatuto Marco del personal estatutario de los servicios de salud", icon: "📋", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t03" },
  { id: "comun-t04", name: "C2 T04: Ordenación Sanitaria Euskadi", shortName: "T04 Ordenación Sanitaria", description: "Ley 8/1997 y ordenación sanitaria del País Vasco", icon: "🏛️", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t04" },
  { id: "comun-t05", name: "C2 T05: D.255 Osakidetza", shortName: "T05 D.255 Osakidetza", description: "Decreto 255 y estructura de Osakidetza", icon: "🏛️", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t05" },
  { id: "comun-t06", name: "C2 T06: OSI Osakidetza", shortName: "T06 OSI Osakidetza", description: "Organización de las OSI de Osakidetza", icon: "🏥", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t06" },
  { id: "comun-t08", name: "C2 T08: Autonomía del Paciente", shortName: "T08 Autonomía Paciente", description: "Ley 41/2002 de autonomía del paciente", icon: "🤝", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t08" },
  { id: "comun-t09", name: "C2 T09: Voluntades Anticipadas", shortName: "T09 Voluntades Anticipadas", description: "Declaración de voluntades anticipadas", icon: "📝", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t09" },
  { id: "comun-t10", name: "C2 T10: Protección de Datos", shortName: "T10 Protección Datos", description: "RGPD y LOPDGDD aplicada al ámbito sanitario", icon: "🔒", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t10" },
  { id: "comun-t11", name: "C2 T11: Igualdad M/H", shortName: "T11 Igualdad M/H", description: "Ley Orgánica 3/2007 de Igualdad efectiva de mujeres y hombres", icon: "⚖️", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t11" },
  { id: "comun-t12", name: "C2 T12: Plan Salud Euskadi 2030", shortName: "T12 Plan Salud 2030", description: "Plan de Salud de Euskadi 2030", icon: "📊", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t12" },
  { id: "comun-t13", name: "C2 T13: Pacto Vasco por la Salud", shortName: "T13 Pacto Vasco Salud", description: "Pacto Vasco por la Salud", icon: "🤝", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t13" },
  { id: "comun-t14", name: "C2 T14: Seguridad del Paciente 2030", shortName: "T14 Seguridad Paciente", description: "Plan de Seguridad del Paciente 2030", icon: "🛡️", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t14" },
  { id: "comun-t15", name: "C2 T15: Plan Igualdad Osakidetza", shortName: "T15 Plan Igualdad", description: "Plan de Igualdad de Osakidetza", icon: "⚖️", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t15" },
  { id: "comun-t16", name: "C2 T16: Normalización del Euskera", shortName: "T16 Euskera", description: "Normalización del Euskera en Osakidetza", icon: "🌿", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t16" },
  { id: "comun-t17", name: "C2 T17: Plan Oncológico Euskadi", shortName: "T17 Plan Oncológico", description: "Plan Oncológico de Euskadi", icon: "🎗️", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t17" },
  { id: "comun-t18", name: "C2 T18: Eutanasia", shortName: "T18 Eutanasia", description: "Ley Orgánica 3/2021 de regulación de la eutanasia", icon: "📜", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t18" },
  { id: "comun-t19", name: "C2 T19: Incompatibilidades AAPP", shortName: "T19 Incompatibilidades", description: "Ley 53/1984 de incompatibilidades del personal de las AAPP", icon: "⛔", category: "comun", color: "text-blue-800", bgColor: "bg-blue-50", borderColor: "border-blue-200", questionFile: "comun-t19" },

  // ── ADMINISTRATIVO C1 (específico) ───────────────────────────────────────
  { id: "adm-eapv-estatuto-autonomia", name: "ADM E01: EAPV Estatuto Autonomía", shortName: "ADM EAPV", description: "Estatuto de Autonomía del País Vasco", icon: "🏛️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-eapv-estatuto-autonomia" },
  { id: "adm-lpac-interesados-y-actos", name: "ADM E02: LPAC Interesados y Actos", shortName: "ADM LPAC Actos", description: "Ley 39/2015 — interesados y actos administrativos", icon: "⚖️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-lpac-interesados-y-actos" },
  { id: "adm-lpac-procedimiento", name: "ADM E03: LPAC Procedimiento", shortName: "ADM LPAC Proc.", description: "Ley 39/2015 — procedimiento administrativo", icon: "⚖️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-lpac-procedimiento" },
  { id: "adm-lpac-recursos", name: "ADM E04: LPAC Recursos", shortName: "ADM LPAC Recursos", description: "Ley 39/2015 — recursos administrativos", icon: "⚖️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-lpac-recursos" },
  { id: "adm-lrjsp-sector-publico", name: "ADM E05: LRJSP Sector Público", shortName: "ADM LRJSP", description: "Ley 40/2015 de Régimen Jurídico del Sector Público", icon: "⚖️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-lrjsp-sector-publico" },
  { id: "adm-ebep-empleado-publico", name: "ADM E06: EBEP Empleado Público", shortName: "ADM EBEP", description: "Estatuto Básico del Empleado Público", icon: "🏢", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-ebep-empleado-publico" },
  { id: "adm-d255-osakidetza-especifico", name: "ADM E07: D.255 Osakidetza", shortName: "ADM D.255", description: "Decreto 255 específico para Administrativo", icon: "🏛️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-d255-osakidetza-especifico" },
  { id: "adm-condiciones-trabajo-osakidetza", name: "ADM E08: Condiciones Trabajo", shortName: "ADM Condiciones", description: "Condiciones de trabajo del personal de Osakidetza", icon: "📋", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-condiciones-trabajo-osakidetza" },
  { id: "adm-segunda-opinion-medica", name: "ADM E11: Segunda Opinión Médica", shortName: "ADM 2ª Opinión", description: "Ley vasca de segunda opinión médica", icon: "🩺", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-segunda-opinion-medica" },
  { id: "adm-prl-prevencion-riesgos", name: "ADM E12: PRL Prevención Riesgos", shortName: "ADM PRL", description: "Ley 31/1995 de Prevención de Riesgos Laborales", icon: "⚠️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-prl-prevencion-riesgos" },
  { id: "adm-prl-atencion-cliente-osaki", name: "ADM E13: PRL Atención al Cliente", shortName: "ADM PRL Cliente", description: "Atención al cliente y PRL en Osakidetza", icon: "⚠️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-prl-atencion-cliente-osaki" },
  { id: "adm-puestos-funcionales", name: "ADM E14: Puestos Funcionales", shortName: "ADM Puestos", description: "Relación de puestos funcionales de Osakidetza", icon: "📊", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-puestos-funcionales" },
  { id: "adm-transparencia-y-buen-gobierno", name: "ADM: Transparencia y Buen Gobierno", shortName: "ADM Transparencia", description: "Ley 19/2013 de Transparencia y Buen Gobierno", icon: "📚", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-transparencia-y-buen-gobierno" },
  { id: "adm-protocolo-acoso-sexual-osaki", name: "ADM: Protocolo Acoso Sexual", shortName: "ADM Acoso Sexual", description: "Protocolo de actuación ante el acoso sexual en Osakidetza", icon: "🛡️", category: "administrativo", color: "text-indigo-800", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", questionFile: "adm-protocolo-acoso-sexual-osaki" },

  // ── AUXILIAR ADMINISTRATIVO C2 (específico) ──────────────────────────────
  { id: "aux-e01", name: "AUX E01: EAPV Estatuto Autonomía", shortName: "AUX EAPV", description: "Estatuto de Autonomía del País Vasco", icon: "🏛️", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e01" },
  { id: "aux-e02", name: "AUX E02: LPAC Interesados y Actos", shortName: "AUX LPAC Actos", description: "Ley 39/2015 — interesados y actos administrativos", icon: "⚖️", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e02" },
  { id: "aux-e03", name: "AUX E03: LPAC Procedimiento", shortName: "AUX LPAC Proc.", description: "Ley 39/2015 — procedimiento administrativo", icon: "⚖️", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e03" },
  { id: "aux-e04", name: "AUX E04: LPAC Recursos", shortName: "AUX LPAC Recursos", description: "Ley 39/2015 — recursos administrativos", icon: "⚖️", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e04" },
  { id: "aux-e05", name: "AUX E05: LRJSP Sector Público", shortName: "AUX LRJSP", description: "Ley 40/2015 de Régimen Jurídico del Sector Público", icon: "⚖️", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e05" },
  { id: "aux-e06", name: "AUX E06: EBEP Empleado Público", shortName: "AUX EBEP", description: "Estatuto Básico del Empleado Público", icon: "🏢", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e06" },
  { id: "aux-e07", name: "AUX E07: D.255 Osakidetza", shortName: "AUX D.255", description: "Decreto 255 específico para Auxiliar Administrativo", icon: "🏛️", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e07" },
  { id: "aux-e08", name: "AUX E08: Condiciones Trabajo", shortName: "AUX Condiciones", description: "Condiciones de trabajo del personal de Osakidetza", icon: "📋", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e08" },
  { id: "aux-e11", name: "AUX E11: Segunda Opinión Médica", shortName: "AUX 2ª Opinión", description: "Ley vasca de segunda opinión médica", icon: "🩺", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e11" },
  { id: "aux-e12", name: "AUX E12: PRL Prevención Riesgos", shortName: "AUX PRL", description: "Ley 31/1995 de Prevención de Riesgos Laborales", icon: "⚠️", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e12" },
  { id: "aux-e13", name: "AUX E13: PRL Atención al Cliente", shortName: "AUX PRL Cliente", description: "Atención al cliente y PRL en Osakidetza", icon: "⚠️", category: "auxiliar", color: "text-emerald-800", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", questionFile: "aux-e13" },

  // ── TÉCNICO SUPERIOR ADM A1 — COMÚN ABC1 (solo TEC) ─────────────────────
  { id: "tec-comun-t01", name: "ABC1 T01: Profesiones Sanitarias", shortName: "T01 Prof. Sanitarias", description: "Ley 44/2003 de Ordenación de Profesiones Sanitarias (TEC)", icon: "🏥", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t01" },
  { id: "tec-comun-t02", name: "ABC1 T02: Cohesión del SNS", shortName: "T02 Cohesión SNS", description: "Ley 16/2003 de Cohesión y Calidad del SNS (TEC)", icon: "🏥", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t02" },
  { id: "tec-comun-t03", name: "ABC1 T03: Estatuto Marco", shortName: "T03 Estatuto Marco", description: "Estatuto Marco del personal estatutario (TEC)", icon: "📋", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t03" },
  { id: "tec-comun-t04", name: "ABC1 T04: Ley 8/1997 Osakidetza", shortName: "T04 Ley 8/1997", description: "Ley 8/1997 de Ordenación Sanitaria de Euskadi", icon: "🏛️", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t04" },
  { id: "tec-comun-t05", name: "ABC1 T05: D.100/2018 OSI", shortName: "T05 D.100/2018 OSI", description: "Decreto 100/2018 de las Organizaciones Sanitarias Integradas", icon: "🏥", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t05" },
  { id: "tec-comun-t06", name: "ABC1 T06: D.147/2015 Derechos", shortName: "T06 Derechos Paciente", description: "Decreto 147/2015 de Derechos del Paciente", icon: "🤝", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t06" },
  { id: "tec-comun-t08", name: "ABC1 T08: Autonomía del Paciente", shortName: "T08 Autonomía Paciente", description: "Ley 41/2002 de autonomía del paciente (TEC)", icon: "🤝", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t08" },
  { id: "tec-comun-t09", name: "ABC1 T09: Voluntades Anticipadas", shortName: "T09 Voluntades", description: "Declaración de voluntades anticipadas (TEC)", icon: "📝", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t09" },
  { id: "tec-comun-t10", name: "ABC1 T10: Protección de Datos", shortName: "T10 RGPD", description: "RGPD y LOPDGDD aplicada al ámbito sanitario (TEC)", icon: "🔒", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t10" },
  { id: "tec-comun-t11", name: "ABC1 T11: Igualdad M/H", shortName: "T11 Igualdad M/H", description: "Ley Orgánica 3/2007 de Igualdad (TEC)", icon: "⚖️", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t11" },
  { id: "tec-comun-t12", name: "ABC1 T12: Plan Salud Euskadi 2030", shortName: "T12 Plan Salud 2030", description: "Plan de Salud de Euskadi 2030 (TEC)", icon: "📊", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t12" },
  { id: "tec-comun-t13", name: "ABC1 T13: Pacto Vasco por la Salud", shortName: "T13 Pacto Vasco", description: "Pacto Vasco por la Salud (TEC)", icon: "🤝", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t13" },
  { id: "tec-comun-t14", name: "ABC1 T14: Seguridad del Paciente", shortName: "T14 Seguridad Paciente", description: "Plan de Seguridad del Paciente (TEC)", icon: "🛡️", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t14" },
  { id: "tec-comun-t15", name: "ABC1 T15: Igualdad, Euskera, Oncología", shortName: "T15 Igualdad Euskera", description: "Igualdad, normalización del euskera y Plan Oncológico (TEC)", icon: "🎗️", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t15" },
  { id: "tec-comun-t16", name: "ABC1 T16: Eutanasia e Incompatibilidades", shortName: "T16 Eutanasia", description: "Ley de eutanasia e incompatibilidades AAPP (TEC)", icon: "📜", category: "tec-comun", color: "text-violet-800", bgColor: "bg-violet-50", borderColor: "border-violet-200", questionFile: "tec-comun-t16" },

  // ── TÉCNICO SUPERIOR ADM A1 — ESPECÍFICO ─────────────────────────────────
  { id: "tec-t01", name: "TEC T01: Constitución Española", shortName: "T01 Constitución", description: "Constitución Española de 1978", icon: "🏛️", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-t01" },
  { id: "tec-t02", name: "TEC T02: Estatuto Autonomía PV", shortName: "T02 EAPV", description: "Estatuto de Autonomía del País Vasco", icon: "🏛️", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-t02" },
  { id: "tec-t03", name: "TEC T03: Ley 7/1981 y D.319/2024", shortName: "T03 Ley 7/1981", description: "Ley 7/1981 del Gobierno Vasco y Decreto 319/2024", icon: "⚖️", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-t03" },
  { id: "tec-t04", name: "TEC T04: Ley 39/2015 y Ley 40/2015", shortName: "T04 LPAC / LRJSP", description: "Procedimiento Administrativo y Régimen Jurídico del Sector Público", icon: "⚖️", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-t04" },
  { id: "tec-t05", name: "TEC T05: Contratos y Transparencia", shortName: "T05 Contratos", description: "Ley de Contratos del Sector Público y Transparencia en Osakidetza", icon: "📄", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-t05" },
  { id: "tec-t06", name: "TEC T06: Ley 11/2022, EBEP", shortName: "T06 Ley 11/2022", description: "Ley 11/2022 de Empleo Público de Euskadi y EBEP", icon: "🏢", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-t06" },
  { id: "tec-t07", name: "TEC T07: Puestos Funcionales y LGSS", shortName: "T07 Puestos Func.", description: "Puestos Funcionales Osakidetza, AVPD y LGSS", icon: "📊", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-t07" },
  { id: "tec-t08", name: "TEC T08: Ley 8/1997, Euskera, PRL", shortName: "T08 Ley 8/1997", description: "Ley 8/1997, D.255/2022, Normalización Euskera, PRL", icon: "⚠️", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-t08" },
  { id: "tec-hacienda-pv",          name: "TEC: Hacienda General PV",       shortName: "TEC Hacienda PV",        description: "DL 1/1997 de la Hacienda General del País Vasco",                                   icon: "💰", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-hacienda-pv" },
  { id: "tec-presupuesto-euskadi",   name: "TEC: Régimen Presupuestario",    shortName: "TEC Presupuesto",        description: "DL 1/2011 Régimen Presupuestario de Euskadi",                                     icon: "📊", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-presupuesto-euskadi" },
  { id: "tec-economia-empresa",      name: "TEC: Economía de la Empresa",    shortName: "TEC Economía Empresa",   description: "Costes, organización, FM/PMM, VAN/TIR, punto muerto, apalancamiento y valoración", icon: "📈", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-economia-empresa" },
  { id: "tec-pgc-contabilidad",      name: "TEC: PGC y Contabilidad",        shortName: "TEC PGC",                description: "Plan General de Contabilidad, Marco Conceptual, NRVs y cuentas anuales",           icon: "📒", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-pgc-contabilidad" },
  { id: "tec-analisis-financiero",   name: "TEC: Análisis Financiero",       shortName: "TEC Análisis Financiero",description: "Ratios financieros, fondo de maniobra, PMM, rentabilidad económica y financiera",   icon: "📉", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-analisis-financiero" },
  { id: "tec-control-publico",       name: "TEC: Control y Auditoría Pública",shortName: "TEC Control Público",   description: "TVCP (Ley 1/1988) y Decreto de control económico interno y contabilidad de la CAE",  icon: "🔍", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-control-publico" },
  { id: "tec-logistica-scm",         name: "TEC: Logística y SCM",           shortName: "TEC Logística",          description: "Cadena de suministro, almacenaje, gestión de stocks y logística hospitalaria",      icon: "📦", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-logistica-scm" },
  { id: "tec-compras",               name: "TEC: Compras y Aprovisionamiento",shortName: "TEC Compras",            description: "Organización de compras, negociación, homologación de proveedores y centralización", icon: "🛒", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-compras" },
  { id: "tec-derecho-aplicado",      name: "TEC: Derecho Aplicado",          shortName: "TEC Derecho Aplicado",   description: "Supuestos de CE, EAPV, LPAC, LCSP, empleo público, Estatuto Marco y PRL",           icon: "⚖️", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-derecho-aplicado" },
  { id: "tec-casos-practicos",       name: "TEC: Casos Prácticos Numéricos", shortName: "TEC Casos Prácticos",    description: "Supuestos numéricos de contabilidad, EFE y análisis financiero",                     icon: "📝", category: "tec-especifico", color: "text-amber-800", bgColor: "bg-amber-50", borderColor: "border-amber-200", questionFile: "tec-casos-practicos" },

  // ── VIRTUAL ───────────────────────────────────────────────────────────────
  {
    id: "mezcla",
    name: "Todos los módulos",
    shortName: "Mezcla",
    description: "Práctica mixta intercalando todos los módulos",
    icon: "🔀",
    category: "virtual",
    color: "text-[#282182]",
    bgColor: "bg-[#e8e7f7]",
    borderColor: "border-[#c5c3e8]",
    questionFile: "mezcla"
  }
];

export function getModule(id: string): Module | undefined {
  return MODULES.find(m => m.id === id);
}

export function getModulesByCategory(category: Module['category']): Module[] {
  return MODULES.filter(m => m.category === category);
}
